### ISSUE TITLE
希望增加保存草稿功能

### ISSUE THREAD

**Issue by Xg436** [mlzzen/open-nga#11]
就是退出时会询问一下是否保存草稿，如果保存的话就把上一次的内容写到输入框了

**Comment by Xg436** [comment]
或者加一个一个复选框

**Comment by mlzzen** [comment]
这个已经加入todo中了

**Comment by mlzzen** [comment]
已添加草稿功能 https://github.com/mlzzen/open-nga/releases/tag/v1.1.1
