### ISSUE TITLE
保存用户头像图片失败

### ISSUE THREAD

**Issue by Landius** [mlzzen/open-nga#15]
如下图，帖子图片可以正常保存，但是点开用户头像保存的时候会失败。
开启日志后，`download/nga_open_source/log/` 下也没有报错信息。
![Screenshot_2024-03-27-01-25-45-901_gov anzong androidnga](https://github.com/mlzzen/open-nga/assets/11910028/d4baaf19-5499-4678-972c-212e86bcbb8a)

**Comment by mlzzen** [comment]
fix 1bc673e1a5eddd98bdb035ed170693e1fde2c5a0
