### ISSUE TITLE
问下 怎么调出2个游戏分区显示？

### ISSUE THREAD

**Issue by maioro** [mlzzen/open-nga#17]
![nga客户端第三个](https://github.com/mlzzen/open-nga/assets/60441085/13dbdb77-d7f9-4c40-92d0-9ab77951ea23)

问下怎么-魔兽世界-和--暴雪游戏--在表头的分区没有了？这是啥缘由？还是说需要自己手动添加的？但还没找到哪里可以更改。如上如图，程序是最新版本，

**Comment by mlzzen** [comment]
因为暴雪太过气人，我把暴雪游戏板块移动到游戏专版里面了。手动添加不了。

**Comment by maioro** [comment]
哦~这样
好吧。理解
