### ISSUE TITLE
感谢老哥改的NGA客户端，就是有一个小问题

### ISSUE THREAD

**Issue by HeTianWei** [mlzzen/open-nga#2]
深色模式下，显示最近使用的表情包会变的不是很清楚
![Screenshot_2023-08-28-00-39-07-830_gov anzong androidnga-edit](https://github.com/mlzzen/open-nga/assets/67769640/a09c90b9-392e-475f-b767-1610f7d09f36)

**Comment by mlzzen** [comment]
修复了 c83325a84f83836aca08781cc889af62c4cfdba3
