### ISSUE TITLE
某个表情的显示问题

### ISSUE THREAD

**Issue by Himetsuru202Icmj** [mlzzen/open-nga#20]
这个点赞的表情，在表情选择和官方app以及官方网页版里面都是显示原来的图，发出去之后在帖子里看到会显示这个墨镜的表情（白天模式和暗黑模式都是这样），另外这个墨镜表情自己在表情选择里也和其他图不太一样
![IMG_20240602_165511](https://github.com/mlzzen/open-nga/assets/94740668/cdba91a1-e815-4570-a1c3-09a4dd2226f6)

**Comment by mlzzen** [comment]
感谢反馈，已修复 355f72a0c14a9322429bbc799c667d30db7a1ebf
