### ISSUE TITLE
Add icon.png

### ISSUE THREAD

**Issue by licaon-kter** [mlzzen/open-nga#23]
to https://github.com/mlzzen/open-nga/tree/main/fastlane/metadata/android/en-US in `images/icon.png`

**Comment by mlzzen** [comment]
added 85257d92c440d3addd525bf9ddabb46cad6142ab

**Comment by licaon-kter** [comment]
@mlzzen pls rename `ic_launcher.png` to `icon.png` as asked :smile:

**Comment by mlzzen** [comment]
> @mlzzen pls rename `ic_launcher.png` to `icon.png` as asked 😄

done
