### ISSUE TITLE
有时会提示Too many follow-up requests: 21

### ISSUE THREAD

**Issue by Xg436** [mlzzen/open-nga#3]
刷nga时间长了会出现，能看一下为啥吗

**Comment by mlzzen** [comment]
能截图看看吗，我在代码中也没搜到too many follow-up requests。

**Comment by Xg436** [comment]
![82CE1C3E11706F6A0FF57F6D997490BE](https://github.com/mlzzen/open-nga/assets/35415329/44064a90-8de6-4b3f-8ce3-9324f194635d)
官方版的也有。不会真的就我一个人遇到这个问题吧

**Comment by Xg436** [comment]
出现这个以后帖子列表和帖子内容都看不了，但是内置浏览器可以看，过个十几分钟就好了。

**Comment by mlzzen** [comment]
这这边没法复现，暂时无法解决

**Comment by Xg436** [comment]
跟网络有关，我网络从wifi或者流量切换一下就好了
