### ISSUE TITLE
是否可以增加保存帖子的功能？

### ISSUE THREAD

**Issue by tangshg** [mlzzen/open-nga#4]
很多帖子存活的时间不长，是不是可以手动保存成pdf或者其他格式？感觉在这里增加保存按钮挺合适的
![IMG_20231008_141801.jpg](https://github.com/mlzzen/open-nga/assets/37105296/f2e6825a-f218-41fe-a4c9-e597814a1551)

**Comment by mlzzen** [comment]
可以考虑实现

**Comment by mlzzen** [comment]
在最新的版本中已经实现把帖子导出成图片，不知道是否满足

**Comment by mlzzen** [comment]
实现了这个功能，但是感觉不太实用，不如手机自己的长截图
